// <auto-generated />
using System;
using FirstCodeAproachOneToMany.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstCodeAproachOneToMany.Migrations
{
    [DbContext(typeof(ScoalaDbContext))]
    [Migration("20240221185003_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirstCodeAproachOneToMany.Models.Clasa", b =>
                {
                    b.Property<int>("ClasaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClasaID"));

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("NrElevi")
                        .HasColumnType("int");

                    b.HasKey("ClasaID");

                    b.ToTable("Clase");
                });

            modelBuilder.Entity("FirstCodeAproachOneToMany.Models.Elev", b =>
                {
                    b.Property<int>("ElevID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElevID"));

                    b.Property<int>("ClasaID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataNasterii")
                        .HasColumnType("datetime2");

                    b.Property<string>("ElevNume")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ElevID");

                    b.HasIndex("ClasaID");

                    b.ToTable("Elevi");
                });

            modelBuilder.Entity("FirstCodeAproachOneToMany.Models.Elev", b =>
                {
                    b.HasOne("FirstCodeAproachOneToMany.Models.Clasa", "Clasa")
                        .WithMany("Elevi")
                        .HasForeignKey("ClasaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clasa");
                });

            modelBuilder.Entity("FirstCodeAproachOneToMany.Models.Clasa", b =>
                {
                    b.Navigation("Elevi");
                });
#pragma warning restore 612, 618
        }
    }
}
